//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextMining.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextMining.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///ab
        ///aba
        ///aba-aba
        ///abad
        ///abadi
        ///abadiah
        ///abah
        ///abai
        ///abaimana
        ///abaka
        ///abaktinal
        ///abakus
        ///abal-abal
        ///aban
        ///abang
        ///abangan
        ///abangga
        ///abar
        ///abatoar
        ///abau
        ///abdas
        ///abdi
        ///abdikasi
        ///abdomen
        ///abdominal
        ///abdu
        ///abduksi
        ///abduktor
        ///abece
        ///aben
        ///aberasi
        ///abet
        ///abian
        ///abid
        ///abidin
        ///abiogenesis
        ///abiosfer
        ///abiotik
        ///abis
        ///abisal
        ///abiseka
        ///abiturien
        ///abjad
        ///abjadiah
        ///ablasi
        ///ablaut
        ///ablepsia
        ///abnormal
        ///abnormalitas
        ///abnus
        ///aboi
        ///abolisi
        ///abonemen
        ///aborsi
        ///abortif
        ///abortus
        ///abrak
        ///abrakadabra
        ///abrar
        ///abras
        ///abrasi
        ///abreaksi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Baseword {
            get {
                return ResourceManager.GetString("Baseword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seorang pemburu yang tidak terlalu berani, sedang mencari jejak seekor singa.
        ///^
        ///&quot;Saya tahu,&quot; kata penebang kayu itu, &quot;sekaligus saya bisa menunjukkan dan memperlihatkan kamu dimana Singa itu berada sekarang.&quot;
        ///^
        ///Sang Pemburu berubah menjadi sangat pucat hingga giginya berbunyi karena gemetaran akibat rasa takut.
        ///^
        ///Jika saja ia melihat adanya tanda-tanda jejak sang Singa atau tahu di mana singa tersebut bersarang.
        ///^
        ///Tidak, terima kasih, saya tidak meminta semua itu, saya hanya mencari jejak kakinya, d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jsastrawi_all_0_1 {
            get {
                object obj = ResourceManager.GetObject("jsastrawi_all_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ada
        ///adalah
        ///adanya
        ///adapun
        ///agak
        ///agaknya
        ///agar
        ///akan
        ///akankah
        ///akhir
        ///akhiri
        ///akhirnya
        ///aku
        ///akulah
        ///amat
        ///amatlah
        ///anda
        ///andalah
        ///antar
        ///antara
        ///antaranya
        ///apa
        ///apaan
        ///apabila
        ///apakah
        ///apalagi
        ///apatah
        ///artinya
        ///asal
        ///asalkan
        ///atas
        ///atau
        ///ataukah
        ///ataupun
        ///awal
        ///awalnya
        ///bagai
        ///bagaikan
        ///bagaimana
        ///bagaimanakah
        ///bagaimanapun
        ///bagi
        ///bagian
        ///bahkan
        ///bahwa
        ///bahwasanya
        ///baik
        ///bakal
        ///bakalan
        ///balik
        ///banyak
        ///bapak
        ///baru
        ///bawah
        ///beberapa
        ///begini
        ///beginian
        ///beginikah
        ///beginilah
        ///begitu
        ///begitukah
        ///begitulah
        ///begi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stopword {
            get {
                return ResourceManager.GetString("Stopword", resourceCulture);
            }
        }
    }
}
